// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoList.DAL.Data;

#nullable disable

namespace ToDoList.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231220143622_AddInitialDataToDatabase")]
    partial class AddInitialDataToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoList.DAL.Entity.ToDoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalDescription")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaskEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TaskStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ToDoTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalDescription = "Just do nothing",
                            Status = 2,
                            TaskEndTime = new DateTime(2023, 12, 21, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2754),
                            TaskStartTime = new DateTime(2023, 12, 20, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2712),
                            TaskTitle = "Do nothing1"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalDescription = "Just do nothing",
                            Status = 1,
                            TaskEndTime = new DateTime(2023, 12, 21, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2760),
                            TaskStartTime = new DateTime(2023, 12, 20, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2758),
                            TaskTitle = "Do nothing2"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalDescription = "Just do nothing",
                            Status = 1,
                            TaskEndTime = new DateTime(2023, 12, 21, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2764),
                            TaskStartTime = new DateTime(2023, 12, 20, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2762),
                            TaskTitle = "Do nothing3"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalDescription = "Just do nothing",
                            Status = 0,
                            TaskEndTime = new DateTime(2023, 12, 22, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2769),
                            TaskStartTime = new DateTime(2023, 12, 20, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2767),
                            TaskTitle = "Do nothing4"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalDescription = "Just do nothing",
                            Status = 0,
                            TaskEndTime = new DateTime(2023, 12, 23, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2773),
                            TaskStartTime = new DateTime(2023, 12, 20, 16, 36, 21, 890, DateTimeKind.Local).AddTicks(2771),
                            TaskTitle = "Do nothing5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
